### PR TITLE
Rerender in order to build Python 3.7 packages

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@ocefpaf any idea why this version conflict is happening on Python 2.7 Windows? 🤔 

```
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 145, in solve_for_diff
    force_remove)
  File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda\lib\site-packages\conda\core\solve.py", line 510, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
  File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 1054, in solve
    self.find_conflicts(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 316, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python=2.7 -> vc[version='>=9,<10.0a0']
  - vc[version='>=14,<15.0a0']
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Strange, I did that locally, thought it was enough... 🤔

**Comment by nicoddemus** [comment]
Thanks @ocefpaf! Ready to be merged I think. 👍

**Comment by ocefpaf** [comment]
You have to rerender after adding the compilers. Do you care about the py27 failure on Windows?

**Comment by nicoddemus** [comment]
> You have to rerender after adding the compilers.

Oh, right, makes sense, thanks. I will try to remember that. 👍 

>  Do you care about the py27 failure on Windows?

Nope, but anyway it seems to have passed just fine now (at least on Azure).

**Pull request merged**
